### PR TITLE
Format using black

### PR DESCRIPTION
**Pull request by rowanc1**
Update typos in makefile

### CODE REVIEW

**Comment by rowanc1** [comment]
I am surprised that this fails, but maybe import order is important?

**Comment by berkanteber** [comment]
> I am surprised that this fails, but maybe import order is important?

In [jtex/\_\_init\_\_.py](https://github.com/curvenote/jtex/blob/b0a927dda4da2b851ffcb49b9502f17a83da85f8/jtex/__init__.py), with the new sorting, it imports `PublicTemplateLoader` class before importing `TemplateLoader`, `TemplateOptions`, `TemplateRenderer` classes.

And while importing `PublicTemplateLoader` class from `PublicTemplateLoader` module, these are imported first: `TemplateLoader`, `TemplateOptions`, `TemplateRenderer`. These were previously imported as classes. However, since with the new sorting they are not yet imported in [jtex/\_\_init\_\_.py](https://github.com/curvenote/jtex/blob/b0a927dda4da2b851ffcb49b9502f17a83da85f8/jtex/__init__.py), they cannot be imported as classes. But, since files with the same names exist, they are now imported as modules. So, imports don't fail, but know these are imported as modules instead of classes.

For example, earlier, `TemplateOptions` was imported as a class in [jtex/PublicTemplateLoader.py](https://github.com/curvenote/jtex/blob/86058fd67beda75a48aa25cbee8ea161fc517478/jtex/PublicTemplateLoader.py), but now `TemplateOptions` is imported as a module and the relevant class is `TemplateOptions.TemplateOptions`.  However, in the rest of the code, `TemplateOptions` is still referenced as if it's a class while it no longer is.

So, yes, the order is important in this case.

**Comment by rowanc1** [comment]
Thanks @berkanteber for this explanation, hoping we can sort this out. :)

**Comment by stevejpurves** [comment]
Closing this PR as we have formatted the code and resolved the issue reported above, in PR https://github.com/curvenote/jtex/pull/9

Thanks again for the pointer @berkanteber, it was very helpful in sorting it out.

**Pull request closed without merging**
